# шаблон:
#- metadata: # То что будет в логах
#      project: nuxt
#      page_type: Главная
#    urls: # ссылки
#      - https://polza.ru/
#    headers: # хедер который будет применятся к запросам на urlы
#      Cookie: ssr=1;nuxt=1
# ----------------------------------------------------------------
configs:
  #- metadata: # То что будет в логах
  #    project: тест
  #    page_type: тест с хедером
  #  urls: # ссылки
  #    - https://example.com/
  #  headers: # хедер который будет применятся к запросам на urlы
  #    Cookie: ssr=1;nuxt=1
  #
  #- metadata: # То что будет в логах
  #    project: тест
  #    page_type: тест без хедера
  #  urls: # ссылки
  #    - https://example.com/
  #  headers: # хедер который будет применятся к запросам на urlы
      
  # ----------------------------------------------------------------
  - metadata: # То что будет в логах
      project: nuxt
      page_type: Главная
    urls: # ссылки
      - https://polza.ru/
    headers: # хедер который будет применятся к запросам на urlы
      Cookie: ssr=1;nuxt=1
    
  - metadata: # То что будет в логах
      project: bitrix
      page_type: Главная
    urls: # ссылки
      - https://polza.ru/
    headers: # хедер который будет применятся к запросам на urlы

  # ----------------------------------------------------------------
  - metadata: # То что будет в логах
      project: nuxt
      page_type: Каталог
    urls: # ссылки
      - https://polza.ru/catalog/lekarstvennye-sredstva/
    headers: # хедер который будет применятся к запросам на urlы
      Cookie: ssr=1;nuxt=1
  
  - metadata: # То что будет в логах
      project: bitrix
      page_type: Каталог
    urls: # ссылки
      - https://polza.ru/catalog/lekarstvennye-sredstva/
    headers: # хедер который будет применятся к запросам на urlы

  # ----------------------------------------------------------------
  - metadata: # То что будет в логах
      project: nuxt
      page_type: Карточка товара
    urls: # ссылки
      - https://polza.ru/catalog/flebodia-600-tabletki-pokryt-plen-ob-600-mg-60-sht_13720/
    headers: # хедер который будет применятся к запросам на urlы
      Cookie: ssr=1;nuxt=1
  
  - metadata: # То что будет в логах
      project: bitrix
      page_type: Карточка товара
    urls: # ссылки
      - https://polza.ru/catalog/flebodia-600-tabletki-pokryt-plen-ob-600-mg-60-sht_13720/
    headers: # хедер который будет применятся к запросам на urlы

